import { Terminal } from '@xterm/xterm'
import { FitAddon } from '@xterm/addon-fit'
import { SearchAddon } from '@xterm/addon-search'
import '@xterm/xterm/css/xterm.css'
import './style.css'

const $ = (q, root = document) => root.querySelector(q)
const $$ = (q, root = document) => [...root.querySelectorAll(q)]
const esc = (s = '') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const state = { me: null, csrf: '', hosts: [], credentials: [], groups: [], tabs: [], active: null, section: 'hosts', theme: readTheme() }

function readTheme(){try{return localStorage.getItem('webssh-theme')==='light'?'light':'dark'}catch{return'dark'}}
function terminalTheme(){return state.theme==='light'?{background:'#f8faf7',foreground:'#263126',cursor:'#397a22',selectionBackground:'#9bc98b66',black:'#243024',green:'#397a22',brightGreen:'#55a735'}:{background:'#090b10',foreground:'#d7dae2',cursor:'#a9ff68',selectionBackground:'#46506a88',black:'#181a20',green:'#9ee86f',brightGreen:'#b8ff86'}}
function applyTheme(theme,persist=true){state.theme=theme==='light'?'light':'dark';document.documentElement.dataset.theme=state.theme;document.documentElement.style.colorScheme=state.theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',state.theme==='light'?'#f4f6f1':'#0b0d12');if(persist){try{localStorage.setItem('webssh-theme',state.theme)}catch{}}state.tabs.forEach(t=>{t.term.options.theme=terminalTheme()});syncThemeButtons()}
function toggleTheme(){applyTheme(state.theme==='dark'?'light':'dark')}
function themeLabel(){return state.theme==='dark'?'☀ 亮色':'☾ 深色'}
function syncThemeButtons(){$$('#theme-toggle, #login-theme').forEach(b=>{b.textContent=themeLabel();b.title=state.theme==='dark'?'切换到亮色主题':'切换到深色主题'});const select=$('#theme-select');if(select)select.value=state.theme}
applyTheme(state.theme,false)

async function api(path, options = {}) {
  const headers = {...(options.headers || {})}
  if (options.body && typeof options.body !== 'string') { headers['Content-Type'] = 'application/json'; options.body = JSON.stringify(options.body) }
  if (!['GET','HEAD'].includes(options.method || 'GET') && state.csrf) headers['X-CSRF-Token'] = state.csrf
  const res = await fetch('/api/v1' + path, {...options, headers})
  if (res.status === 204) return null
  const data = await res.json().catch(() => ({}))
  if (!res.ok) throw Object.assign(new Error(data.error?.message || `请求失败 (${res.status})`), {code:data.error?.code, data:data.error?.data, status:res.status})
  return data
}
function toast(message, kind = '') { const n = $('#toast'); n.textContent = message; n.className = `show ${kind}`; clearTimeout(n._t); n._t = setTimeout(() => n.className = '', 2800) }
function icon(name) { const paths={terminal:'<path d="m5 7 5 5-5 5M12 19h7"/>',host:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 8h.01M7 12h.01M7 16h.01M11 8h6M11 12h6M11 16h4"/>',key:'<circle cx="8" cy="15" r="4"/><path d="m11 12 8-8M15 8l3 3M17 6l3 3"/>',audit:'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.09A1.7 1.7 0 0 0 8.94 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.56-1.03H3v-4h.09A1.7 1.7 0 0 0 4.6 8.94a1.7 1.7 0 0 0-.34-1.88L4.2 7l2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10 3.05V3h4v.09a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06L19.8 7l-.06.06a1.7 1.7 0 0 0-.34 1.88A1.7 1.7 0 0 0 20.95 10H21v4h-.09A1.7 1.7 0 0 0 19.4 15Z"/>',logout:'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',star:'<path d="m12 2 3 6 7 .9-5 4.8 1.2 6.8L12 17.3l-6.2 3.2L7 13.7 2 8.9 9 8Z"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||''}</svg>` }

function loginView() { $('#app').innerHTML = `<main class="login"><section class="login-copy"><div class="brand"><span>${icon('terminal')}</span> Orbit SSH</div><div><p class="eyebrow">SELF-HOSTED GATEWAY</p><h1>你的基础设施，<br><em>近在指尖。</em></h1><p>一处管理所有 SSH 会话。完整 PTY、tmux 与移动端支持，密钥始终留在服务端。</p></div><div class="signal"><span></span> 局域网安全连接</div></section><section class="login-panel"><button id="login-theme" class="theme-toggle" type="button"></button><form id="login-form"><div class="mini-logo">${icon('terminal')}</div><h2>欢迎回来</h2><p>登录以访问你的终端工作区</p><label>用户名<input name="username" autocomplete="username" value="admin" required></label><label>密码<input name="password" type="password" autocomplete="current-password" placeholder="输入密码" required></label><button class="primary" type="submit">进入工作区 <span>→</span></button><div class="form-error"></div></form><footer>WebSSH Gateway <b>v1.0</b> · 端到端加密凭据</footer></section></main>`;$('#login-theme').onclick=toggleTheme;syncThemeButtons();$('#login-form').onsubmit=async e=>{e.preventDefault();const btn=$('button[type="submit"]',e.currentTarget);btn.disabled=true;try{const d=await api('/auth/login',{method:'POST',body:Object.fromEntries(new FormData(e.currentTarget))});state.me=d.user;state.csrf=d.csrf_token;await boot()}catch(err){$('.form-error').textContent=err.message}finally{btn.disabled=false}} }
async function init(){try{const d=await api('/me');state.me=d.user;state.csrf=d.csrf_token;await boot()}catch{loginView()}}
async function boot(){await Promise.all([loadHosts(),loadCredentials(),loadGroups()]);appView();renderHosts()}
async function loadHosts(q=''){state.hosts=(await api('/hosts'+(q?`?q=${encodeURIComponent(q)}`:''))).hosts}
async function loadCredentials(){state.credentials=(await api('/credentials')).credentials}
async function loadGroups(){state.groups=(await api('/groups')).groups}

function appView(){ $('#app').innerHTML=`<div class="shell"><aside><div class="brand side"><span>${icon('terminal')}</span><strong>Orbit</strong><small>SSH Gateway</small></div><nav><button class="active" data-section="hosts">${icon('host')}主机</button><button data-section="credentials">${icon('key')}凭据</button><button data-section="audit">${icon('audit')}审计日志</button><button data-section="settings">${icon('settings')}设置</button></nav><div class="aside-foot"><div class="avatar">${esc(state.me.username[0].toUpperCase())}</div><div><strong>${esc(state.me.username)}</strong><small>${esc(state.me.role)}</small></div><button id="logout" title="退出">${icon('logout')}</button></div></aside><div class="main"><header><button class="mobile-menu">☰</button><div class="global-search">${icon('search')}<input id="search" placeholder="搜索主机、地址或标签…"><kbd>⌘ K</kbd></div><button id="theme-toggle" class="theme-toggle" type="button"></button><button class="ghost" id="new-group">新建分组</button><button class="primary compact" id="new-host">${icon('plus')} 添加主机</button></header><section id="content"></section><section id="workspace" class="workspace hidden"><div id="tabbar" class="tabbar"></div><div id="terminals" class="terminals"></div><div class="mobile-keys"><button data-key="\u001b">Esc</button><button data-key="\t">Tab</button><button data-latch="ctrl">Ctrl</button><button data-latch="alt">Alt</button><button data-key="\u001b[D">←</button><button data-key="\u001b[A">↑</button><button data-key="\u001b[B">↓</button><button data-key="\u001b[C">→</button><button data-key="\u001b[5~">PgUp</button><button data-key="\u001b[6~">PgDn</button><button data-action="paste">Paste</button></div></section></div></div><div id="modal-root"></div>`
  $$('nav button').forEach(b=>b.onclick=()=>showSection(b.dataset.section));$('#new-host').onclick=()=>hostModal();$('#new-group').onclick=groupModal;$('#theme-toggle').onclick=toggleTheme;syncThemeButtons();$('#logout').onclick=logout;$('#search').oninput=debounce(async e=>{await loadHosts(e.target.value);renderHosts()},180);$('.mobile-menu').onclick=()=>$('aside').classList.toggle('open');document.addEventListener('keydown',globalKeys);$('.mobile-keys').onclick=mobileKey
}
function showSection(name){state.section=name;$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===name));$('#content').classList.remove('hidden');$('#workspace').classList.add('hidden');if(name==='hosts')renderHosts();if(name==='credentials')renderCredentials();if(name==='audit')renderAudit();if(name==='settings')renderSettings()}
function renderHosts(){state.section='hosts';const groups=[{id:null,name:'全部主机'},...state.groups];$('#content').innerHTML=`<div class="page-head"><div><p class="eyebrow">INFRASTRUCTURE</p><h2>主机</h2><p>${state.hosts.length} 个已保存目标</p></div><div class="view-actions"><button class="icon-btn active">▦</button><button class="icon-btn">☷</button></div></div><div class="group-chips">${groups.map((g,i)=>`<button class="${i===0?'active':''}" data-group="${g.id??''}">${esc(g.name)}</button>`).join('')}</div><div class="host-grid"></div>`;renderHostGrid(state.hosts);$$('.group-chips button').forEach(b=>b.onclick=()=>{$$('.group-chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderHostGrid(b.dataset.group?state.hosts.filter(h=>String(h.group_id)===b.dataset.group):state.hosts)})}
function renderHostGrid(items){$('.host-grid').innerHTML=items.length?items.map(h=>`<article class="host-card" data-id="${h.id}"><div class="host-top"><div class="host-glyph">${icon('terminal')}</div><button class="star ${h.favorite?'on':''}" title="收藏">${icon('star')}</button></div><h3>${esc(h.name)}</h3><p class="address">${esc(h.username)}@${esc(h.hostname)}:${h.port}</p><div class="tags">${h.group_name?`<span>${esc(h.group_name)}</span>`:''}${h.tags.split(',').filter(Boolean).slice(0,2).map(t=>`<span>${esc(t.trim())}</span>`).join('')}<span class="encoding">${h.encoding}</span></div><div class="host-foot"><span class="dot"></span><small>${h.host_key_fingerprint?'已验证密钥':'待验证密钥'}</small><button class="more" title="编辑">•••</button><button class="connect">连接 <b>↗</b></button></div></article>`).join(''):`<div class="empty"><div>${icon('host')}</div><h3>还没有主机</h3><p>先添加凭据，再保存你的第一个 SSH 目标。</p><button class="primary" id="empty-add">添加主机</button></div>`;$$('.connect').forEach(b=>b.onclick=e=>{e.stopPropagation();connectHost(+b.closest('article').dataset.id)});$$('.more').forEach(b=>b.onclick=e=>{e.stopPropagation();hostModal(state.hosts.find(h=>h.id===+b.closest('article').dataset.id))});$('#empty-add')?.addEventListener('click',()=>hostModal())}

function modal(title,body,onSubmit,{wide=false}={}){const root=$('#modal-root');root.innerHTML=`<div class="modal-back"><section class="modal ${wide?'wide':''}"><div class="modal-head"><h3>${title}</h3><button type="button" class="close">×</button></div><form>${body}<div class="form-error"></div></form></section></div>`;const close=()=>root.innerHTML='';$('.close',root).onclick=close;$('.modal-back',root).onclick=e=>{if(e.target===e.currentTarget)close()};$('form',root).onsubmit=async e=>{e.preventDefault();try{await onSubmit(Object.fromEntries(new FormData(e.currentTarget)),close)}catch(err){$('.form-error',root).textContent=err.message}};return {root,close}}
function hostModal(h={}){if(!state.credentials.length){toast('请先创建 SSH 凭据','warn');showSection('credentials');return}const groups=state.groups.map(g=>`<option value="${g.id}" ${g.id===h.group_id?'selected':''}>${esc(g.name)}</option>`).join('');const creds=state.credentials.map(c=>`<option value="${c.id}" ${c.id===h.credential_id?'selected':''}>${esc(c.name)}</option>`).join('');modal(h.id?'编辑主机':'添加 SSH 主机',`<div class="form-grid"><label class="full">显示名称<input name="name" value="${esc(h.name)}" placeholder="例如：生产服务器" required></label><label class="span2">主机地址<input name="hostname" value="${esc(h.hostname)}" placeholder="192.168.1.10 或 server.lan" required></label><label>端口<input name="port" type="number" value="${h.port||22}" min="1" max="65535"></label><label>用户名<input name="username" value="${esc(h.username)}" required></label><label>凭据<select name="credential_id">${creds}</select></label><label>分组<select name="group_id"><option value="">无分组</option>${groups}</select></label><label>默认编码<select name="encoding"><option ${h.encoding!=='GB18030'?'selected':''}>UTF-8</option><option ${h.encoding==='GB18030'?'selected':''}>GB18030</option></select></label><label class="span2">标签<input name="tags" value="${esc(h.tags)}" placeholder="linux, production"></label><label class="full">连接后执行（可选）<input name="auto_command" value="${esc(h.auto_command)}" placeholder="tmux new-session -A -s main"></label><label class="full">备注<textarea name="notes" rows="3">${esc(h.notes)}</textarea></label><label class="check full"><input name="favorite" type="checkbox" ${h.favorite?'checked':''}> 加入收藏</label></div><div class="modal-actions">${h.id?'<button type="button" class="danger delete-host">删除</button><button type="button" class="ghost copy-host">复制</button>':''}<span></span><button type="button" class="ghost cancel">取消</button><button class="primary" type="submit">保存主机</button></div>`,async(d,close)=>{d.port=+d.port;d.credential_id=+d.credential_id;d.group_id=d.group_id?+d.group_id:null;d.favorite=d.favorite==='on';await api(h.id?`/hosts/${h.id}`:'/hosts',{method:h.id?'PUT':'POST',body:d});close();await loadHosts();renderHosts();toast('主机已保存')},{wide:true});$('.cancel').onclick=()=>$('.close').click();$('.delete-host')?.addEventListener('click',async()=>{if(confirm(`删除主机“${h.name}”？`)){await api(`/hosts/${h.id}`,{method:'DELETE'});$('.close').click();await loadHosts();renderHosts();toast('主机已删除')}});$('.copy-host')?.addEventListener('click',async()=>{await api(`/hosts/${h.id}/copy`,{method:'POST'});$('.close').click();await loadHosts();renderHosts();toast('已创建主机副本')})}
function renderCredentials(){$('#content').innerHTML=`<div class="page-head"><div><p class="eyebrow">SECURITY</p><h2>凭据</h2><p>敏感内容以 AES-256-GCM 加密，绝不返回浏览器</p></div><button class="primary compact" id="add-cred">${icon('plus')} 添加凭据</button></div><div class="list-panel">${state.credentials.map(c=>`<div class="list-row"><div class="round-icon">${icon('key')}</div><div><strong>${esc(c.name)}</strong><small>${c.type==='key'?'SSH 私钥':'密码'}${c.username?' · '+esc(c.username):''}</small></div><span class="pill">${c.type}</span><button class="ghost edit-cred" data-id="${c.id}">编辑</button></div>`).join('')||'<div class="empty compact-empty">暂无凭据</div>'}</div>`;$('#add-cred').onclick=()=>credentialModal();$$('.edit-cred').forEach(b=>b.onclick=()=>credentialModal(state.credentials.find(c=>c.id===+b.dataset.id)))}
function credentialModal(c={}){modal(c.id?'编辑凭据':'添加凭据',`<label>凭据名称<input name="name" value="${esc(c.name)}" required></label><label>类型<select name="type" id="cred-type"><option value="password" ${c.type!=='key'?'selected':''}>密码</option><option value="key" ${c.type==='key'?'selected':''}>SSH 私钥</option></select></label><label>默认用户名（可选）<input name="username" value="${esc(c.username)}"></label><div id="secret-fields"></div><div class="modal-actions">${c.id?'<button type="button" class="danger delete-cred">删除</button>':''}<span></span><button type="button" class="ghost cancel">取消</button><button class="primary">保存凭据</button></div>`,async(d,close)=>{await api(c.id?`/credentials/${c.id}`:'/credentials',{method:c.id?'PUT':'POST',body:d});close();await loadCredentials();renderCredentials();toast('凭据已安全保存')});const fields=()=>{$('#secret-fields').innerHTML=$('#cred-type').value==='password'?`<label>密码<input name="password" type="password" ${c.id?'placeholder="留空表示不修改"':'required'}></label>`:`<label>OpenSSH / PEM 私钥<textarea name="private_key" rows="8" ${c.id?'placeholder="留空表示不修改"':'required'}></textarea></label><label>私钥口令（可选）<input name="passphrase" type="password"></label>`};$('#cred-type').onchange=fields;fields();$('.cancel').onclick=()=>$('.close').click();$('.delete-cred')?.addEventListener('click',async()=>{if(confirm(`删除凭据“${c.name}”？`)){try{await api(`/credentials/${c.id}`,{method:'DELETE'});$('.close').click();await loadCredentials();renderCredentials();toast('凭据已删除')}catch(e){$('.form-error').textContent=e.message}}})}
function groupModal(){modal('新建分组',`<label>分组名称<input name="name" placeholder="例如：生产环境" required autofocus></label><div class="modal-actions"><span></span><button type="button" class="ghost cancel">取消</button><button class="primary">创建分组</button></div>`,async(d,close)=>{d.sort_order=state.groups.length;await api('/groups',{method:'POST',body:d});close();await loadGroups();await loadHosts();renderHosts();toast('分组已创建')});$('.cancel').onclick=()=>$('.close').click()}
async function renderAudit(){$('#content').innerHTML='<div class="loading">加载审计日志…</div>';try{const d=await api('/audit?limit=200');$('#content').innerHTML=`<div class="page-head"><div><p class="eyebrow">OBSERVABILITY</p><h2>审计日志</h2><p>仅记录管理与连接事件，不记录终端输入</p></div></div><div class="audit-table"><div class="table-head"><span>时间</span><span>操作者</span><span>事件</span><span>对象</span></div>${d.events.map(e=>`<div class="table-row"><span>${new Date(e.created_at+'Z').toLocaleString()}</span><span>${esc(e.username||'系统')}</span><span><b class="event-dot"></b>${esc(e.action)}</span><span>${esc(e.object_type)} ${e.object_id??''}</span></div>`).join('')}</div>`}catch(e){toast(e.message,'error')}}
async function renderSettings(){$('#content').innerHTML='<div class="loading">加载设置…</div>';const d=await api('/settings');$('#content').innerHTML=`<div class="page-head"><div><p class="eyebrow">PREFERENCES</p><h2>设置</h2><p>系统级运行参数与账户安全</p></div></div><form id="settings-form" class="settings-card"><h3>外观</h3><div class="form-grid"><label>界面主题<select id="theme-select" name="theme"><option value="dark">深色</option><option value="light">亮色</option></select></label></div><h3>终端体验</h3><div class="form-grid"><label>Scrollback 行数<input name="scrollback" type="number" min="1000" max="100000" value="${d.terminal.scrollback||8000}"></label><label>字体大小<input name="font_size" type="number" min="10" max="28" value="${d.terminal.font_size||14}"></label></div><h3>会话</h3><label class="check"><input name="close_confirm" type="checkbox" ${d.session.close_confirm?'checked':''}> 关闭活跃终端前确认</label><button class="primary">保存设置</button></form><form id="password-form" class="settings-card password-card"><h3>修改登录密码</h3><div class="form-grid"><label>当前密码<input name="current_password" type="password" autocomplete="current-password" required></label><label>新密码（至少 12 位）<input name="new_password" type="password" minlength="12" autocomplete="new-password" required></label></div><button class="primary">更新密码</button></form>`;syncThemeButtons();$('#theme-select').onchange=e=>applyTheme(e.target.value);$('#settings-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));applyTheme(f.theme);await api('/settings',{method:'PUT',body:{terminal:{...d.terminal,scrollback:+f.scrollback,font_size:+f.font_size},session:{...d.session,close_confirm:f.close_confirm==='on'}}});toast('设置已保存')};$('#password-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{await api('/me/password',{method:'PUT',body:f});e.currentTarget.reset();toast('登录密码已更新')}catch(err){toast(err.message,'error')}}}

class TerminalSession { constructor(host){this.host=host;this.id=`t${Date.now()}${Math.random()}`;this.status='connecting';this.ctrl=false;this.alt=false;this.term=new Terminal({cursorBlink:true,convertEol:false,scrollback:8000,fontFamily:'"JetBrains Mono","SFMono-Regular",Consolas,monospace',fontSize:14,theme:terminalTheme()});this.fit=new FitAddon();this.search=new SearchAddon();this.term.loadAddon(this.fit);this.term.loadAddon(this.search)}
  mount(){const el=document.createElement('div');el.className='terminal-pane';el.dataset.id=this.id;el.innerHTML='<div class="terminal-mount"></div><div class="term-search hidden"><input placeholder="查找终端历史"><button>×</button></div>';$('#terminals').append(el);this.el=el;this.term.open($('.terminal-mount',el));this.fit.fit();this.term.focus();this.term.onData(data=>this.sendInput(data));this.term.onResize(debounce(size=>this.sendControl({type:'resize',...size}),70));new ResizeObserver(()=>{if(this===activeTab())requestAnimationFrame(()=>this.fit.fit())}).observe(el);const input=$('.term-search input',el);input.oninput=()=>this.search.findNext(input.value,{incremental:true});$('.term-search button',el).onclick=()=>this.toggleSearch(false);this.open()}
  open(){const proto=location.protocol==='https:'?'wss':'ws';const url=`${proto}://${location.host}/api/v1/terminal/${this.host.id}?cols=${this.term.cols}&rows=${this.term.rows}`;this.ws=new WebSocket(url);this.ws.binaryType='arraybuffer';this.ws.onopen=()=>{this.setStatus('connecting');this.term.writeln('\x1b[38;5;244m正在建立安全 SSH 连接…\x1b[0m')};this.ws.onmessage=e=>{if(e.data instanceof ArrayBuffer){this.term.write(new Uint8Array(e.data));return}let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='ready'){this.setStatus('connected');this.term.clear()}if(m.type==='exit'){this.setStatus('disconnected');this.term.writeln('\r\n\x1b[38;5;244m会话已结束\x1b[0m')}if(m.type==='error'){this.setStatus('failed');this.term.writeln(`\r\n\x1b[31m${m.message}\x1b[0m`);if(m.code==='SSH_HOST_KEY_UNKNOWN')confirmHostKey(this,m.data);else if(m.code==='SSH_HOST_KEY_MISMATCH')hostKeyMismatch(this,m.data)}};this.ws.onclose=()=>{if(this.status==='connected'||this.status==='connecting')this.setStatus('disconnected')}}
  sendInput(data){if(this.ws?.readyState!==1)return;let out=data;if(this.ctrl&&out.length===1){out=String.fromCharCode(out.toUpperCase().charCodeAt(0)&31);this.ctrl=false;updateLatch()}if(this.alt&&out.length){out='\u001b'+out;this.alt=false;updateLatch()}this.ws.send(new TextEncoder().encode(out))}
  sendControl(m){if(this.ws?.readyState===1)this.ws.send(JSON.stringify({v:1,...m}))}
  setStatus(v){this.status=v;renderTabs()}
  setEncoding(v){this.host.encoding=v;this.sendControl({type:'encoding',encoding:v});this.term.writeln(`\r\n\x1b[38;5;244m会话编码已切换为 ${v}\x1b[0m`)}
  show(){this.el.classList.add('active');requestAnimationFrame(()=>{this.fit.fit();this.term.focus()})}
  hide(){this.el.classList.remove('active')}
  close(){if(this.status==='connected'&&!confirm(`关闭 ${this.host.name} 的活跃终端？`))return false;this.ws?.close();this.term.dispose();this.el.remove();return true}
  toggleSearch(show=true){$('.term-search',this.el).classList.toggle('hidden',!show);if(show){$('.term-search input',this.el).focus()}else this.term.focus()}
}
function connectHost(id){let h=state.hosts.find(x=>x.id===id);if(!h)return;let t=new TerminalSession(h);state.tabs.push(t);state.active=t.id;$('#content').classList.add('hidden');$('#workspace').classList.remove('hidden');t.mount();activateTab(t.id);renderTabs()}
function activeTab(){return state.tabs.find(t=>t.id===state.active)}
function activateTab(id){state.active=id;state.tabs.forEach(t=>t.id===id?t.show():t.hide());renderTabs()}
function renderTabs(){$('#tabbar').innerHTML=state.tabs.map(t=>`<button class="term-tab ${t.id===state.active?'active':''}" data-id="${t.id}"><span class="status ${t.status}"></span>${esc(t.host.name)}<small>${t.status}</small><b>×</b></button>`).join('')+`<button class="back-hosts">＋</button><div class="tab-spacer"></div><select class="live-encoding" title="当前终端编码"><option ${activeTab()?.host.encoding!=='GB18030'?'selected':''}>UTF-8</option><option ${activeTab()?.host.encoding==='GB18030'?'selected':''}>GB18030</option></select><button class="term-find" title="搜索">${icon('search')}</button>`;$$('.term-tab').forEach(b=>{b.onclick=e=>{if(e.target.tagName==='B'){const t=state.tabs.find(x=>x.id===b.dataset.id);if(t.close()){state.tabs=state.tabs.filter(x=>x!==t);if(!state.tabs.length)showSection('hosts');else activateTab(state.tabs.at(-1).id)}}else activateTab(b.dataset.id)}});$('.back-hosts').onclick=()=>showSection('hosts');$('.term-find').onclick=()=>activeTab()?.toggleSearch(true);$('.live-encoding').onchange=e=>activeTab()?.setEncoding(e.target.value)}
async function confirmHostKey(t,data){modal('验证 SSH 主机密钥',`<div class="hostkey-warning"><b>首次连接</b><p>请通过可信渠道核对以下指纹。确认后将固定此 Host Key。</p><code>${esc(data.key_type)}<br>${esc(data.fingerprint)}</code></div><div class="modal-actions"><span></span><button type="button" class="ghost cancel">取消</button><button class="primary">确认并重新连接</button></div>`,async(_,close)=>{await api(`/hosts/${t.host.id}/verify-host-key`,{method:'POST',body:{fingerprint:data.fingerprint}});close();await loadHosts();t.ws?.close();t.term.writeln('\r\n\x1b[32m主机密钥已固定，正在重连…\x1b[0m');t.open()});$('.cancel').onclick=()=>$('.close').click()}
function hostKeyMismatch(t,data){modal('主机密钥已变化',`<div class="hostkey-warning dangerbox"><b>连接已被阻断</b><p>这可能意味着服务器重装，也可能是中间人攻击。请先由管理员核实，不会自动接受新密钥。</p><code>当前：${esc(data.fingerprint)}<br>预期：${esc(data.expected)}</code></div><div class="modal-actions"><span></span><button type="button" class="primary cancel">关闭</button></div>`,async()=>{}) ;$('.cancel').onclick=()=>$('.close').click()}
function mobileKey(e){const b=e.target.closest('button');if(!b)return;const t=activeTab();if(!t)return;if(b.dataset.latch){t[b.dataset.latch]=!t[b.dataset.latch];updateLatch();return}if(b.dataset.action==='paste'){navigator.clipboard.readText().then(x=>t.sendInput(x)).catch(()=>toast('浏览器未授予剪贴板读取权限','warn'));return}t.sendInput(b.dataset.key)}
function updateLatch(){const t=activeTab();$$('[data-latch]').forEach(b=>b.classList.toggle('latched',!!t?.[b.dataset.latch]))}
function globalKeys(e){if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showSection('hosts');$('#search').focus()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='f'&&!$('#workspace').classList.contains('hidden')){e.preventDefault();activeTab()?.toggleSearch(true)}}
async function logout(){try{await api('/auth/logout',{method:'POST'})}finally{state.tabs.forEach(t=>t.ws?.close());state.me=null;state.csrf='';document.removeEventListener('keydown',globalKeys);loginView()}}
function debounce(fn,ms){let t;return function(...args){clearTimeout(t);t=setTimeout(()=>fn.apply(this,args),ms)}}
init()
